mod vm;
mod darwin;
mod encoder;

use clap::{Parser, Subcommand};
use darwin::EvolutionaryEngine;
use std::fs;

#[derive(Parser)]
#[command(name = "Genesis")]
#[command(about = "Evolutionary VM Engine", long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Evolve a genotype to solve the specified target logic
    Evolve {
        #[arg(short, long, default_value = "logic")]
        target: String,
        #[arg(short, long, default_value_t = 5000)]
        generations: usize,
    },
    /// Transpile a hex-encoded DNA sequence into native Rust source code
    Transpile {
        #[arg(short, long)]
        input: String,
        #[arg(short, long, default_value = "output.rs")]
        output: String,
    },
}

fn main() {
    let cli = Cli::parse();

    match &cli.command {
        Commands::Evolve { target, generations } => {
            println!("Starting Parallel Evolution Engine...");
            println!("Target Evaluation Mode: {}", target);
            
            let mut engine = EvolutionaryEngine::new(target);
            engine.evolve(*generations);
            
            println!("Evolution Complete.");
            
            let best = &engine.population[0];
            println!("Optimal Fitness: {}", best.fitness);
            
            // Verification Trace
            let mut vm = vm::AstVM::new();
            println!("\nVerification Trace:");
            if target == "logic" {
                let table = [(0, 0, 0), (0, 1, 1), (1, 0, 1), (1, 1, 0)];
                for (a, b, expected) in table.iter() {
                    vm.load(&best.sequence);
                    vm.registers[0] = *a;
                    vm.registers[1] = *b;
                    vm.run();
                    println!("{} XOR {} = {} (Expected {}) | Cycles: {}", a, b, vm.registers[0], expected, vm.cycles);
                }
            } else if target == "fault_tolerance" {
                let tests = [2, 5, 10];
                for x in tests.iter() {
                    // Clean Run
                    vm.load(&best.sequence);
                    vm.registers[0] = *x;
                    vm.run();
                    println!("f({}) = {} (Clean Run)", x, vm.registers[0]);
                    
                    // Radiation Runs
                    for trial in 1..=3 {
                        vm.load(&best.sequence);
                        vm.registers[0] = *x;
                        vm.run_with_radiation(0.02);
                        let success = if vm.registers[0] == x * 2 { "PASS" } else { "FAIL" };
                        println!("  Radiation Trial {} -> f({}) = {} [{}]", trial, x, vm.registers[0], success);
                    }
                }
            } else if target == "fibonacci" {
                vm.load(&best.sequence);
                vm.run();
                println!("Fibonacci Output Sequence:");
                for val in vm.output_buffer.iter() {
                    print!("{} ", val);
                }
                println!("\nCycles: {}", vm.cycles);
            }

            // Export to file
            let hex_string = encoder::encode(&best.sequence);
            println!("\nEncoded Sequence (Hex): {}", hex_string);
            
            match fs::write("program.hex", &hex_string) {
                Ok(_) => println!("Successfully exported sequence to 'program.hex'"),
                Err(e) => eprintln!("Failed to export sequence: {}", e),
            }
        }
        Commands::Transpile { input, output } => {
            println!("Transpiling sequence from {}...", input);
            let hex_str = fs::read_to_string(input).unwrap_or_else(|_| {
                eprintln!("Failed to read input file.");
                std::process::exit(1);
            });

            let sequence = encoder::decode(hex_str.trim());
            let mut rust_code = String::new();
            rust_code.push_str("// Auto-generated by Genesis Transpiler\n");
            rust_code.push_str("fn main() {\n");
            rust_code.push_str("    let mut r: [i32; 8] = [0; 8];\n");
            rust_code.push_str("    let mut m: [u8; 1024] = [0; 1024];\n\n");


            rust_code.push_str("    let mut ip: i32 = 0;\n");
            rust_code.push_str("    let mut cycles = 0;\n");
            rust_code.push_str("    loop {\n");
            rust_code.push_str("        if cycles >= 10000 { break; }\n");
            rust_code.push_str("        cycles += 1;\n");
            rust_code.push_str("        match ip {\n");

            for (i, op) in sequence.iter().enumerate() {
                rust_code.push_str(&format!("            {} => {{\n", i));
                match op {
                    vm::Opcode::Nop => rust_code.push_str("                ip += 1;\n"),
                    vm::Opcode::Inc(reg) => rust_code.push_str(&format!("                r[{}] = r[{}].wrapping_add(1);\n                ip += 1;\n", reg, reg)),
                    vm::Opcode::Dec(reg) => rust_code.push_str(&format!("                r[{}] = r[{}].wrapping_sub(1);\n                ip += 1;\n", reg, reg)),
                    vm::Opcode::Add(d, s) => rust_code.push_str(&format!("                r[{}] = r[{}].wrapping_add(r[{}]);\n                ip += 1;\n", d, d, s)),
                    vm::Opcode::Sub(d, s) => rust_code.push_str(&format!("                r[{}] = r[{}].wrapping_sub(r[{}]);\n                ip += 1;\n", d, d, s)),
                    vm::Opcode::Mul(d, s) => rust_code.push_str(&format!("                r[{}] = r[{}].wrapping_mul(r[{}]);\n                ip += 1;\n", d, d, s)),
                    vm::Opcode::Div(d, s) => rust_code.push_str(&format!("                if r[{}] != 0 {{ r[{}] = r[{}].wrapping_div(r[{}]); }}\n                ip += 1;\n", s, d, d, s)),
                    vm::Opcode::Mov(d, s) => rust_code.push_str(&format!("                r[{}] = r[{}];\n                ip += 1;\n", d, s)),
                    vm::Opcode::Ldi(d, imm) => rust_code.push_str(&format!("                r[{}] = {};\n                ip += 1;\n", d, imm)),
                    vm::Opcode::Jmp(offset) => rust_code.push_str(&format!("                ip = ip.wrapping_add({});\n", offset)),
                    vm::Opcode::Jz(reg, offset) => rust_code.push_str(&format!("                if r[{}] == 0 {{ ip = ip.wrapping_add({}); }} else {{ ip += 1; }}\n", reg, offset)),
                    vm::Opcode::IoOut(reg) => rust_code.push_str(&format!("                println!(\"{{}}\", r[{}]);\n                ip += 1;\n", reg)),
                    vm::Opcode::Ld(d, a) => rust_code.push_str(&format!("                r[{}] = m[(r[{}] as usize) % 1024] as i32;\n                ip += 1;\n", d, a)),
                    vm::Opcode::St(a, s) => rust_code.push_str(&format!("                m[(r[{}] as usize) % 1024] = (r[{}] & 0xFF) as u8;\n                ip += 1;\n", a, s)),
                    vm::Opcode::Hlt => rust_code.push_str("                break;\n"),
                }
                rust_code.push_str("            }\n");
            }
            
            rust_code.push_str("            _ => break,\n");
            rust_code.push_str("        }\n    }\n");
            rust_code.push_str("    println!(\"Final Result (R0): {}\", r[0]);\n");
            rust_code.push_str("    println!(\"Press Enter to exit...\");\n");
            rust_code.push_str("    let _ = std::io::stdin().read_line(&mut String::new());\n");
            rust_code.push_str("}\n");

            match fs::write(output, &rust_code) {
                Ok(_) => println!("Successfully transpiled to '{}'", output),
                Err(e) => eprintln!("Failed to write transpiled code: {}", e),
            }
        }
    }
}
